language: python
python:
    - 3.6

install:
    - pip install --pre -e .[tests]

script:
    - pytest

after_success:
    - coveralls
    - pip uninstall -y kapre

after_failure:
    - pip uninstall -y kapre
