language: python
python:
    - "3.6"
    - "3.7"

install:
    - pip install tox-travis
    - pip install --pre -e .

script:
    - tox

after_success:
    - coveralls
    - pip uninstall -y kapre

after_failure:
    - pip uninstall -y kapre
